# Generated by Django 4.2.2 on 2023-08-08 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=255)),
                ('startLatitude', models.FloatField()),
                ('startLongitude', models.FloatField()),
                ('destination', models.CharField(max_length=255)),
                ('destinationLatitude', models.FloatField()),
                ('destinationLongitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
