# Generated by Django 4.2.2 on 2023-08-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_navigation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='destinationLatitude',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='destinationLongitude',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='start',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='startLatitude',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='startLongitude',
        ),
    ]
