# Generated by Django 4.2.2 on 2023-08-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_navigation_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_navigations', to='location.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='navigation',
            name='start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='start_navigations', to='location.location'),
            preserve_default=False,
        ),
    ]
