# Generated by Django 4.2.2 on 2023-08-09 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_delete_profilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilephotos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
