# Generated by Django 4.2.2 on 2023-08-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_location_created_by_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
